import Head from 'next/head'
import {
  Container,
  Description,
  Intro,
  TopRecipes, 
  SampleRecipe,
  ByDish,
  ByDietaryRestriction,
  SubmitRecipe,
  FeaturedReviews,
  IntroContainer
} from '../components/sharedstyles'
import Card from '../components/cards'
import Review from '../components/reviews'
import Link from 'next/link'

//submit form function 
// call router.push(url=recipe name)
//mkae a dynamic  

const fetcher = url => fetch(url).then(r => r.json())


export default function Home() {
  return (
    <Container>
      <Head>
        <title>Em + K</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro>
        <IntroContainer>
          <h1 className='cookbookname'>Kaylee's Cookbook</h1>
          <p>
          Explore our vast collection of recipes, submit your own creations, and share your love of cooking with others. Get started today.
          </p>
          <button className='getcooking'>
            Get Cooking
          </button>
        </IntroContainer>
      </Intro>

      <TopRecipes>
        <div className='CardGrid'>
         <Link href="/toprecipes"><h1 className='top'>Top Rated Recipes</h1></Link>
          <p>Discover our community's favorite dishes. From easy weeknight meals to exquisite dinner party options, there's something here for everyone. Try our:</p>
          <Card />
         </div>
      </TopRecipes>
      <SampleRecipe>
        <div className='recipeContainer'> 
          <h1>Easy Homemade Pizza Recipe</h1>
          <p>Who doesn't love pizza? This easy homemade pizza recipe is perfect for a fun night in with the family. Follow these simple steps and enjoy:</p>
          <div>

            <div className='innerrecipe'>
            <div className='recipeImage'>
            <img src="https://cdn.loveandlemons.com/wp-content/uploads/2019/06/homemade-pizza-2.jpg" alt="homemade pizza"></img>
            </div>

            <div className='recipeSteps'>
              <div>
                <h2>Step 1</h2>
                <p>Preheat oven to 425°F (220°C).</p>
              </div>

              <div>
                <h2>Step 2</h2>
                <p>Roll out pizza dough and place on baking sheet.</p>
              </div>

              <div>
                <h2>Step 3</h2>
                <p>Add your favorite toppings such as tomato sauce, cheese, pepperoni, and vegetables.</p>
              </div>

              <div>
                <h2>Step 4</h2>
                <p>Bake for 10-12 minutes, or until crust is golden brown and cheese is melted.</p>
              </div>

              <div>
                <h2>Step 5</h2>
                <p>Serve hot and enjoy!</p>
              </div>
            </div>
           

            </div>
            
            <div>
              <h2>Reviews:</h2>
              <ul>
                <li>"This recipe is so easy and delicious. My family loved it!" - Sarah</li>
                <li>"I never thought I could make pizza this good at home. Thanks for the recipe!" - John</li>
                <li>"I've tried a lot of homemade pizza recipes, and this is by far the best." - Emily</li>
              </ul>
            </div>
          </div>
        </div>
       
      </SampleRecipe>
      <ByDish>
        <div className='DishGrid'>
          <Link href="/findmeals"><h1>Find Meals By Ingredients </h1></Link>
          <p>Find your favorite recipes by dish, from appetizers to desserts. Choose from:</p>
         
          <div className='item appitem'>
            <h2>Appetizers</h2>
            <ul>
              <li>Garlic Bread</li>
              <li>Spinach dip</li>
              <li>Caesar Salad</li>
            </ul>
          </div>
          <div className='item mainitem'>
            <h2>Main Courses</h2>
            <ul>
              <li>Garlic Bread</li>
              <li>Spinach dip</li>
              <li>Caesar Salad</li>
            </ul>
          </div>
          <div className='item dessertitem'>
            <h2>Desserts</h2>
            <ul>
              <li>Garlic Bread</li>
              <li>Spinach dip</li>
              <li>Caesar Salad</li>
            </ul>
          </div>
          
        </div>
      </ByDish>

      <ByDietaryRestriction>
        <div className='dietarycontainer'>
          <h1>Search By Dietary Restriction</h1>
          <p>Find recipes that work for you, even if you have dietary restrictions or food allergies. Try these:</p>
          <form action="/action_page.php">
            <input type="text" placeholder="Search.." name="search" />
            <button type="submit">Submit</button>
          </form>
          <div className='item appitem'>
            <h2>Gluten-Free</h2>
            <ul>
              <li>Baked Cod with Lemon</li>
              <li>Crustless Quiche</li>
              <li>Caesar Salad</li>
            </ul>
          </div>
          <div className='item mainitem'>
            <h2>Vegan</h2>
            <ul>
              <li>Garlic Bread</li>
              <li>Spinach dip</li>
              <li>Caesar Salad</li>
            </ul>
          </div>
          <div className='item dessertitem'>
            <h2>Low-Carb</h2>
            <ul>
              <li>Garlic Bread</li>
              <li>Spinach dip</li>
              <li>Caesar Salad</li>
            </ul>
          </div>
        </div>
      </ByDietaryRestriction>

      <SubmitRecipe>
        <div className='submitcontainer'>
          <div>
            <img className='submitimage' src="https://img.freepik.com/premium-photo/topdown-view-kitchen-table-with-ingredients-utensils-open-cookbook_645697-7959.jpg"></img>
          </div>
          <div className='submittext'> 
            <h1>Submit Recipe</h1>
            <p>Got a recipe that you'd like to share with our community? We'd love to hear from you! Submit your recipe today and see it featured on our site.</p>
            <button>Share Your Recipe</button>
          </div>
        </div>
        
      </SubmitRecipe>

      <FeaturedReviews>
      <div className='reviewscontainer'>
          <h1 className='top'>Featured Reviews</h1>
          <p>Check out what our community members are saying about their favourite recipes:</p>
          <Review />
         </div>
      </FeaturedReviews>


     
    </Container>
  )
}
